### PR TITLE
New mandrel releases (20.3.1.1.Final and 21.0.0.0.Final)

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by zakkak** [comment]
@cescoffier there was an issue with the assets of https://github.com/graalvm/mandrel/releases/edit/mandrel-21.0.0.0.Final that should now be fixed. Could you please re-run the CI?

**Comment by cescoffier** [comment]
I've restarted the CI.

**Review by jerboaa — APPROVED** [review]
Seems good to me.

**Comment by zakkak** [comment]
@cescoffier can you please make these images public?

**Comment by cescoffier** [comment]
deployment in progress.

**Pull request merged**
