### PR TITLE
Add Automated tests of container images

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by cescoffier** [comment]
@zakkak you may want to have a look.

**Review by zakkak — APPROVED** [review]
I am not really qualified to perform this review (no experience with testing images with cekit) but FWIW it looks good to me!

Some questions/suggestions:

1. Is there any way to check that the `native-image --version` matches the image tag?
2. I suggesting adding something like:
```
    Scenario: Check that native-image is GraalVM
        Given container is started with entrypoint native-image --version
        Then container log should contain GraalVM and should not contain Mandrel
```
for `ubi-quarkus-native-image` and :
```
    Scenario: Check that native-image is Mandrel
        Given container is started with entrypoint native-image --version
        Then container log should contain GraalVM and Mandrel
```
for `ubi-quarkus-mandrel`.

Thanks

**Comment by cescoffier** [comment]
Unfortunately, I didn't find a way to get the tags (I'm a noob).
I've added the GraalVM / Mandrel checks.

**Comment by zakkak** [comment]
> Unfortunately, I didn't find a way to get the tags (I'm a noob).
> I've added the GraalVM / Mandrel checks.

Great, thanks @cescoffier !

**Pull request merged**
