### PR TITLE
Update mandrel images with new version scheme

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by zakkak** [comment]
The failure seems to be irrelevant to this PR, the tests seem unhappy with GraalVM 20.2 images.

```
Out of date version of GraalVM detected: GraalVM Version 20.2.0 (Java Version 11.0.8). Quarkus currently supports 21.0. Please upgrade GraalVM to this version.
```

at https://github.com/quarkusio/quarkus-images/runs/2011064320?check_suite_focus=true#step:4:2810

**Review by jerboaa — APPROVED** [review]
This looks good.

For reference we need to re-release those images because of a mandrel version scheme issue. See: https://github.com/graalvm/mandrel/issues/218

With the new releases the above issue no longer occurs.

**Comment by cescoffier** [comment]
You will investigate the CI issue later today. The s2i test application uses a version of Quarkus preventing the use of outdated GraalVM version

**Comment by cescoffier** [comment]
I merged it manually to get the CI fix.

**Comment by jerboaa** [comment]
Thanks!

**Pull request closed without merging**
