### PR TITLE
Add mandrel 20.1.0.1.Alpha2 image

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by jerboaa** [comment]
@cescoffier Would you be able to help with this getting reviewed and pushed? We'd like to get the community mandrel image updated to a Mandrel version which is based on an actual General Availability release of OpenJDK (11.0.8+10 in this case). The current live image is built on an Early Access (EA) version. Thanks!

**Comment by zakkak** [comment]
@cescoffier Could you also take care of making this public when it gets pushed to quay.io? We still don't have access there :)

**Comment by jerboaa** [comment]
Thanks very much, @cescoffier!

**Comment by cescoffier** [comment]
@zakkak It's online: https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags.

**Comment by zakkak** [comment]
Thanks a lot @cescoffier ! 

Please let us know if there is any way we can ease some of the burden of getting the images out.

**Pull request merged**
