### PR TITLE
feat: Update to GraalVM 19.3.0.2

### PR DESCRIPTION
**Pull request by machi1990**
/cc @cescoffier @gsmet 

Will be needed for https://github.com/quarkusio/quarkus/pull/6364

PS: It is my first time I am opening a PR in this repo, some guidance will be needed.

### CODE REVIEW

**Comment by cescoffier** [comment]
Look mostly good, you forgot to update: https://github.com/quarkusio/quarkus-images/blob/master/image.yaml#L5

**Comment by machi1990** [comment]
> Look mostly good, you forgot to update: https://github.com/quarkusio/quarkus-images/blob/master/image.yaml#L5

Thanks @cescoffier for the review. Good catch, I have updated the file.

**Comment by gsmet** [comment]
Hmmm, wouldn't it be possible to have some variables? It looks very error prone to chang these versions all around the place.

Not saying we should do that now but might be something to consider for the future.

**Comment by cescoffier** [comment]
Unfortunately no.
I’ve tried a few approaches, not a single one worked. You always hit some limitation of one of the tool somewhere.

Not doing the last update would erase the tag on quay (well replace it). We want to be able to do that when we mess up the image creation (it happens already). But here it’s an update, so we need to bump the version.

Note that anyway, you need to update the SHA manually to verify the download.

**Comment by cescoffier** [comment]
The CI is now going to build the new image and deploy them on Quay.

**Comment by cescoffier** [comment]
Hum.... It seems the the MD5 is wrong:
[31m2020-01-02 04:48:53,307 cekit        ERROR    The md5 computed for the '/var/lib/jenkins/.cekit/cache/2dd73804-2043-4aa6-8709-b933369cb9e2' file ('85a65a665e87a743c703f0ad5d0db085') doesn't match the 'c8e3345a5f4e97ce3ffe468e53fe54d7' value[0m


Did you try building it?

**Comment by cescoffier** [comment]
Can you open a new PR fixing the MD5?

**Comment by machi1990** [comment]
Oh my bad, I generated a random `md5`. Sorry about that. Let me update them after making sure that the images are built on my machine.

**Comment by gsmet** [comment]
> I generated a random md5.

Considering how weak md5 is, it was worth a try :).

**Pull request merged**
