### PR TITLE
Adds Mandrel 20.2.0.0.Final release

### PR DESCRIPTION
**Pull request by Karm**
* Upgrades to the latest OpenJDK 11.0.9 GA.
* See release notes: https://github.com/graalvm/mandrel/releases/tag/mandrel-20.2.0.0.Final

ping @jerboaa  @zakkak

### CODE REVIEW

**Comment by cescoffier** [comment]
Fighting some issues with the image publication. Will merge (After approval) after I found the issue with Quay.

**Comment by Karm** [comment]
@cescoffier O.K.  There should be nothing extraordinary here. Just a mechanical update, version bump + removal of libffi-devel that was already approved and merged in  https://github.com/quarkusio/quarkus-images/pull/108.

**Review by zakkak — APPROVED** [review]
LGTM

**Review by jerboaa — APPROVED** [review]
Looks fine to me.

**Comment by cescoffier** [comment]
I just resolved the quay issue!

**Comment by cescoffier** [comment]
Published!

**Comment by zakkak** [comment]
Thank you Clement!

**Pull request merged**
