### PR TITLE
Adds Mandrel 21.3.5.1 and 22.3.1.0

### PR DESCRIPTION
**Pull request by Karm**
Hello @cescoffier, I am not sure this is all it takes to add our new builds with this new quarkus-images layout.  Is it O.K.?

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
Thanks!

**Comment by Karm** [comment]
@cescoffier @galderz 

Hmm, regarding aarch64, 

```
15:03:21 + sudo podman pull quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17
15:03:21 Trying to pull quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17...
15:03:23 Getting image source signatures
15:03:23 Copying blob sha256:eab66ae1072584be15ec16ad61037111bc2770ba0c04a1443506c619d6663267
15:03:23 Copying blob sha256:9ab09967f36098f7f24cc31c86a223a2d072e85af5850f816fcf4eed474425d0
15:03:23 Copying blob sha256:48b45ae49ef36420f9cd731b3d317743bc4eaf4e1698df4390d01ae385286f44
15:03:23 Copying blob sha256:1958fb4a2e29032875e6aab14daa8202ea7cc67c165108f89ac356176693c471
15:03:23 Copying blob sha256:92c2d296d0b6d6ca6ecc8a267e31ac9fbfc400e950d6ac13b527d2491f12214e
15:03:23 Copying blob sha256:7c43afe89fe5992e1ce31051380245b3200dca4523f78f88d242720f28c3c7a9
15:03:24 Copying blob sha256:b368d4a72a0f15518c6d99f2465812c42e6f913fa377077fcbef42b69b7faf31
15:03:24 Copying blob sha256:054d71205ffd0cd07ecdf4cea943f7ad3e9edf205bc3facbcf526ef998fe9059
15:03:24 Copying blob sha256:1e148dd47edc6856fe317ddef64200a8789db265cb55fbfaa6fea2ca8ce46a72
15:03:24 Copying blob sha256:d0b1e8ff275e4b593be8f220e94a3bda1b8b65a63c7cea18b187fce61c90c412
15:03:25 Copying blob sha256:5662194b70d5985bbc5c75f0af1b2ad337f76671229e0786f0ec57538fea16af
15:03:25 Copying blob sha256:b3810bf0cc1ab36444b3727075018e9c8d0da7750ac5d04179398b8d3d2daae2
15:03:25 Copying blob sha256:9a513560a01b8e99ce276a61aca48791469a13f32c35ade797116284ceb1bd4f
15:03:25 Copying blob sha256:443b54f38e673fe12303efdfa7b8ef5fb56ce62463b4a01458ab7bc3d89cc86f
15:03:26 Copying blob sha256:f5807665836a5627af2bfa435a41cb37b9385cdf6485256f6371a2450cecb514
15:03:27 Copying blob sha256:759787b3b7d0db131e717e873e26070811d94504dd96d4551d78b1df3adc165a
15:03:27 Copying blob sha256:f5db8849c192ba4f67cc6a492f6c234fd99a6e673e86a4aa2dee2acd44ba6443
15:03:27 Copying blob sha256:95ccf41a5a48e32367e8a94effa6ac61c596e392f20421ae6f6c01a993811fcd
15:03:40 Copying config sha256:7230f890fe53f33ce6e59f4aba09434dc172ba6cac632e011cd5e672ee98b725
15:03:40 Writing manifest to image destination
15:03:40 Storing signatures
15:03:40 WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })
15:03:40 7230f890fe53f33ce6e59f4aba09434dc172ba6cac632e011cd5e672ee98b725
```

...am I supposed to explicitly tell something to podman?  Doesn't it work like a standard multiarch Docker image?

**Comment by cescoffier** [comment]
I get a slightly different behavior on my side (using docker). Let me have a look.

**Comment by cescoffier** [comment]
I removed and re-pulled the manifest and it's working. 
Did you inspect the manifest?

**Comment by Karm** [comment]
@cescoffier I was just being dumb. 

It works on my arm systems just fine.
I was erroneously using the obsoleted:
https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags

instead of the correct:
https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags

I will fix our docs :man_facepalming:

**Pull request merged**
