### PR TITLE
Issue 2

### PR DESCRIPTION
**Pull request by kameshsampath**
- Rebased maven image from the `centos-quarkus-native-image`
- updated maven image README with more details and example

### CODE REVIEW

**Comment by kameshsampath** [comment]
FYIA: @cescoffier  @Sanne  @@vorburger

**Comment by Sanne** [comment]
Many thanks!

Question for you all: what's a reasonable way to test PRs affecting our docker images?

**Comment by cescoffier** [comment]
There is an issue: unordered build. This PR introduces a dependency between 2 images. Unfortunately our current setup (Quay) does not allow us to express this. 

It means that if I update GraalVM, there is a chance (basically will happen every time for me) that the depending image get builds and fails because the ‘from’ is not built yet. We would need to trigger manually the build once the ‘from’ image is built.

**Comment by kameshsampath** [comment]
> Many thanks!
> 
> Question for you all: what's a reasonable way to test PRs affecting our docker images?

I usuall use the framework [dgoss](https://github.com/aelsabbahy/goss/tree/master/extras/dgoss)

**Comment by kameshsampath** [comment]
> There is an issue: unordered build. This PR introduces a dependency between 2 images. Unfortunately our current setup (Quay) does not allow us to express this. It means that if I update GraalVM, there is a chance (basically will happen every time for me) that the depending image get builds and fails because the ‘from’ is not built yet. We would need to trigger manually the build once the ‘from’ image is built.

@cescoffier - I would prefer to move this out of quay auto build and then add a CI like cricleci or travis  to do the build and push. IMHO Circle CI is better as it has wrokflow and dependency builds to defined.

**Comment by cescoffier** [comment]
Do you mean having a script building all of them in order?

**Comment by cescoffier** [comment]
@kameshsampath if you can open a PR with integration tests that would be great!

**Comment by vorburger** [comment]
@kameshsampath if you split the 4 things done here (1. centos-quarkus-maven/Dockerfile FROM centos-quarkus-native-image instead of centos:7, 2. README md -> adoc pure format change, 3. README improvements, 4. entrypoint-run.sh clean up) it's easier to get things reviewed and merged separately - just a thought.

**Comment by kameshsampath** [comment]
> Do you mean having a script building all of them in order?

@cescoffier  yes or CircleCI has the workflow where we can define steps, where we can define the image order.

**Comment by kameshsampath** [comment]
> if you split the 4 things done here (1. centos-quarkus-maven/Dockerfile FROM centos-quarkus-native-image instead of centos:7, 2. README md -> adoc pure format change, 3. README improvements, 4. entrypoint-run.sh clean up) it's easier to get things reviewed and merged separately - just a thought. 

@vorburger  - the sh change is very minor space change, just to make it clear i did split them in to multiple commits . Was more of question of size of changes vs number of issues. But pointed noted and will handle it from next commit

**Comment by kameshsampath** [comment]
> @kameshsampath if you can open a PR with integration tests that would be great!

yeah I will get PR with image test approach for the maven image. we can then repeat the same for others

**Comment by kameshsampath** [comment]
/do-not-merge
@cescoffier  - we can hold this merge until CI strategies is freezed

**Comment by cescoffier** [comment]
Closing -This PR is outdated.

**Pull request closed without merging**
