### PR TITLE
Mandrel/GraalVM JDK 22 release

### PR DESCRIPTION
**Pull request by Karm**
JDK 22.0 release.

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM. Thanks @Karm

**Review by cescoffier — APPROVED** [review]
Awesome! Thanks!

**Comment by Karm** [comment]
Failure
```
[INFO] 🐋	ERROR: failed to solve: rpc error: code = Unknown desc = write /opt/graalvm/lib/truffle/truffle-api.jar: no space left on device
```

rerunning....

**Comment by Karm** [comment]
@cescoffier Any insight into:

```
[INFO] 🐋	#25 sending tarball 13.7s done
[INFO] 🐋	#25 ERROR: rpc error: code = Unknown desc = write /opt/graalvm/lib/src.zip: no space left on device
[INFO] 🐋	------
[INFO] 🐋	 > exporting to docker image format:
[INFO] 🐋	------
[INFO] 🐋	------
[INFO] 🐋	 > importing to docker:
[INFO] 🐋	------
[INFO] 🐋	ERROR: failed to solve: rpc error: code = Unknown desc = write /opt/graalvm/lib/src.zip: no space left on device
[INFO] java.lang.RuntimeException: Unable to build image for /home/runner/work/quarkus-images/quarkus-images/quarkus-native-s2i/target/docker/ubi-quarkus-graalvmce-s2i:22.3.3-java17-arm64.Dockerfile
```

**Comment by cescoffier** [comment]
I believe it's a disk space issue. Unfortunately I cannot build locally due to the docker desktop removal :-(

**Comment by Karm** [comment]
@cescoffier 

> I believe it's a disk space issue.

I won't argue with that :grinning:

**Comment by cescoffier** [comment]
Yes, or we need to split the build

**Comment by cescoffier** [comment]
@zakkak aren't you in PTO? (If not, welcome back!)

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Right now, the failing build is building:

quay.io/quarkus/ubi-quarkus-graalvmce-s2i   jdk-22.0.0-arm64                              53 seconds ago       1.53GB
quay.io/quarkus/ubi-quarkus-graalvmce-s2i   jdk-21.0.2-amd64   11c4ac1fc877   About a minute ago   1.47GB
quay.io/quarkus/ubi-quarkus-graalvmce-s2i   jdk-21.0.2-arm64   67ea9481fe87   2 minutes ago        1.44GB
quay.io/quarkus/ubi-quarkus-graalvmce-s2i   jdk-21.0.0-amd64   14b591e9cf50   3 minutes ago        1.47GB
quay.io/quarkus/ubi-quarkus-graalvmce-s2i   jdk-21.0.0-arm64   82e3dad2740b   4 minutes ago        1.44GB
quay.io/quarkus/ubi-quarkus-graalvmce-s2i   jdk-17.0.8-amd64   1dda67a8e6ad   5 minutes ago        1.49GB
quay.io/quarkus/ubi-quarkus-graalvmce-s2i   jdk-17.0.8-arm64   b316487db4c8   6 minutes ago        1.46GB


As suggested, we could remove 21.0.0

**Comment by Karm** [comment]
@cescoffier Hmm,  removing JDK 21.0.0 from the picture didn't help.
Docker system prune didn't help either.

Looking at the log, 

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   49G   24G  68% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
```

`/mnt/` seems to have more space than root mount. I'll try to use that.

BTW:
```
Installing QEMU static binaries
  /usr/bin/docker run --rm --privileged tonistiigi/binfmt:latest --install all
  installing: arm64 OK
  installing: arm OK
  installing: ppc64le OK
  installing: mips64le OK
  installing: mips64 OK
  installing: s390x OK
  installing: riscv64 OK
```

Seems like we are pulling some superfluous QEMU support for additional archs. Gonna take a look.

**Comment by Karm** [comment]
@cescoffier  Limiting platforms to arm64 and amd64 has helped. Ready to be merged now.

**Comment by cescoffier** [comment]
Awesome! Thanks!

**Pull request merged**
