### PR TITLE
Update the different images to GraalVM 19.2.0.1

### PR DESCRIPTION
**Pull request by gastaldi**
@cescoffier please review. Needed for https://github.com/quarkusio/quarkus/pull/4043

### CODE REVIEW

**Comment by cescoffier** [comment]
Thanks, I will have a look ASAP. Right now I can download the new GraalVM using the conference Wifi....

**Comment by gsmet** [comment]
@cescoffier man, you're at CodeOne, they might have a local mirror of the Oracle stuff :).

**Comment by cescoffier** [comment]
@gsmet I'm now on a different wifi, so I should be able to deploy the image in a few minutes.

**Comment by cescoffier** [comment]
Images deployed!

**Pull request merged**
