### PR TITLE
Add GraalVM CE 20.3.1

### PR DESCRIPTION
**Pull request by zakkak**
20.3-java11 tag intentionally not updated until thinks get tested in Quarkus.

### CODE REVIEW

**Comment by zakkak** [comment]
```
Docker: I/O error occurred: Corrupted file, digest does not match. Expected 66:16:cd:4b:41:c3:61:23:53:f1:1f:61:a5:1b:77:f8:e7:b2:be:a2:2f:c3:d0:a2:8e:ae:ce:86:d8:db:58:04, got d7:e2:85:4a:8f:08:6e:aa:98:2e:36:53:e2:45:39:8d:91:2a:ff:dc:51:9b:ee:cc:2d:49:bb:a8:b8:23:8e:0e
```

@cescoffier can you please rerun? I am afraid we might be running out of space in the runner :/

**Comment by cescoffier** [comment]
I've relauched the CI. Yes, we may run into a disk space issue again...

**Review by cescoffier — APPROVED** [review]

**Comment by zakkak** [comment]
This time it was a network issue :/ :
```
error: cannot update repo 'ubi-8-appstream': Yum repo downloading error: Downloading error(s): repodata/1d5f648eed4144ac75cc9f905ae032e1d1cd6d50cd4bbd36f961208b08667757-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/451b6d2943773e756ed25191161875ed3f8e15c0891150fcc6818de5fba50082-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/a27718cc28ec6d71432e0ef3e6da544b7f9d93f6bb7d0a55aacd592d03144b70-comps.xml - Cannot download, all mirrors were already tried without success; repodata/fd2e9ca0620c6615385f4edd77f0be5ad6444ec409649ad23cc0322995c415fd-modules.yaml.gz - Cannot download, all mirrors were already tried without success; repodata/90db73b87a4e4d5c21c6ae41a641e0a9dfcc150ad423ae95714b3c9630c8e978-updateinfo.xml.gz - Cannot download, all mirrors were already tried without success; Last error: Curl error (7): Couldn't connect to server for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/repodata/1d5f648eed4144ac75cc9f905ae032e1d1cd6d50cd4bbd36f961208b08667757-primary.xml.gz []
```

**Comment by zakkak** [comment]
It keeps getting better:

```
Run jbang/bin/jbang .github/build-images.java .github/distroless-images.yaml
  jbang/bin/jbang .github/build-images.java .github/distroless-images.yaml
  shell: /bin/bash -e {0}
[jbang] Resolving dependencies...
[jbang]     Resolving info.picocli:picocli:4.5.0...Done
[jbang]     Resolving org.zeroturnaround:zt-exec:1.11...Done
[jbang]     Resolving com.github.docker-java:docker-java:3.2.5...Done
[jbang]     Resolving com.github.docker-java:docker-java-transport-okhttp:3.2.5...Done
[jbang]     Resolving com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.2...Done
[jbang]     Resolving org.slf4j:slf4j-api:1.7.30...Done
[jbang]     Resolving org.slf4j:slf4j-simple:1.7.30...Done
[jbang] Dependencies resolved
[jbang] Building jar...
Note: .github/build-images.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
The configuration file /home/runner/work/quarkus-images/quarkus-images/.github/distroless-images.yaml does not exist - exiting
```

**Comment by cescoffier** [comment]
I merged it manually.

**Comment by zakkak** [comment]
Thanks @cescoffier! Can you also please mark it as publicly accessible?

**Comment by cescoffier** [comment]
Oh forgot to trigger the deployment. Let me do that right away.

**Pull request closed without merging**
