### PR TITLE
Adds Mandrel 20.1.0.3.Final release

### PR DESCRIPTION
**Pull request by Karm**
SSIA

### CODE REVIEW

**Comment by jerboaa** [comment]
This upgrades OpenJDK to the latest security update 11.0.9 too.

**Review by jerboaa — APPROVED** [review]
Looks fine to me.

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
LGTM @zakkak can you have a look?

**Review by zakkak — APPROVED** [review]
LGTM as well :+1: 
Thanks @Karm

**Pull request merged**
