### PR TITLE
Upgrade to Gradle 6.9

### PR DESCRIPTION
**Pull request by ggrebert**
Upgrade to Gradle version to use the same version installed in the wrapper of Quarkus.

### CODE REVIEW

**Comment by ggrebert** [comment]
@gsmet The latest gradle version is `7.2`.
Do you want to keep the `6.9` version or use the latest version ?

**Comment by cescoffier** [comment]
We can update I guess.

**Review by cescoffier — APPROVED** [review]

**Comment by ggrebert** [comment]
Hello @cescoffier 

OK. A new PR or I amend this commit ?

**Comment by cescoffier** [comment]
New PR is good.

**Pull request closed without merging**
