### PR TITLE
Update to GraalVM 19.3.1

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by cescoffier** [comment]
let's see what the CI says....

**Comment by cescoffier** [comment]
Going to trigger the deployment of the image (as soon as I found the right curl command :-))

**Comment by geoand** [comment]
Let me know when you have it so I can verify that the image works properly on my machine

**Comment by cescoffier** [comment]
@geoand just follow https://github.com/quarkusio/quarkus-images/commit/e391ec4a39b92854419a4e14e2f7ea3ba510738a/checks?check_suite_id=401920973. (forgot that to trigger the deployment, it must have a green build of master)

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
