### PR TITLE
Integrate GraalVM 22.3.0

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by Eng-Fouad** [comment]
According to the build logs, it didn't build 22.3 mandrel images:

> Run docker images
> REPOSITORY                                          TAG                           IMAGE ID       CREATED          SIZE
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.2.0.0-Final-java[1](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:1)[7](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:8)-amd64   42ed[8](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:9)b67f[9](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:10)9e   41 seconds ago   1GB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.2.0.0-Final-java17-arm64   91965693e747   2 minutes ago    995MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.2.0.0-Final-java11-amd64   bc0982890cdd   3 minutes ago    995MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.2.0.0-Final-java11-arm64   ac1d665fc9c9   4 minutes ago    982MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.1.0.0-Final-java17-amd64   dc946a2c685c   5 minutes ago    1GB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.1.0.0-Final-java17-arm64   3f1d6ec08ef5   7 minutes ago    993MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.1.0.0-Final-java11-amd64   073c5396d291   8 minutes ago    990MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.1.0.0-Final-java11-arm64   b5ca5afddd88   9 minutes ago    977MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.0.0.2-Final-java17-amd64   d526d9fb9550   [10](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:11) minutes ago   989MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.0.0.2-Final-java17-arm64   a1f5759c7724   12 minutes ago   975MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.0.0.2-Final-java[11](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:12)-amd64   32b[12](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:13)0ea99e4   [13](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:14) minutes ago   976MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   22.0.0.2-Final-java11-arm64   751fc729556a   15 minutes ago   962MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   21.3-java17                   878690869331   17 minutes ago   990MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   21.3.3.0-Final-java17-amd64   878690869331   17 minutes ago   990MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   21.3-java11                   0eb115e3e7aa   18 minutes ago   980MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   21.3.3.0-Final-java11-amd64   0eb115e3e7aa   18 minutes ago   980MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   21.3.2.0-Final-java17-amd64   af930286c56c   19 minutes ago   991MB
> quay.io/quarkus/ubi-quarkus-mandrel-builder-image   21.3.2.0-Final-java11-amd64   eda217d37008   21 minutes ago   976MB
> moby/buildkit                                       buildx-stable-1               a2d3f10918c4   7 days ago       [14](https://github.com/quarkusio/quarkus-images/actions/runs/3326601394/jobs/5500466918#step:9:15)2MB
> tonistiigi/binfmt                                   latest                        354472a37893   2 months ago     60.2MB

**Comment by cescoffier** [comment]
Yes, mandrel 22.3 is not yet available.

**Comment by Eng-Fouad** [comment]
I see.

I tried to use the new image, but I think it is not available on quay.io yet:

> Could not build image: manifest for quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3.0-java19 not found: manifest unknown: manifest unknown

**Comment by cescoffier** [comment]
It's not available yet. I need to run some tests first. Will take a day or two.

**Pull request merged**
