### PR TITLE
Mandrel 21.3.3.0-Final and 22.2.0.0-Final July 2022 CPU

### PR DESCRIPTION
**Pull request by Karm**

### CODE REVIEW

**Comment by Karm** [comment]
@zakkak @cescoffier https://github.com/graalvm/mandrel/releases/tag/mandrel-22.2.0.0-Final might have been in DRAFT state the second this CI was started, so if the download fails, restart the CI, please...

**Review by zakkak — APPROVED** [review]
LGTM. Thanks @Karm!

I think we should remove 22.0 mandrel modules at this point, in case you want to squeeze it in the same commit.

**Comment by Karm** [comment]
> LGTM. Thanks @Karm!
> 
> I think we should remove 22.0 mandrel modules at this point, in case you want to squeeze it in the same commit.

How about we do a cleanup with the LTS? Like "when LTS comes, all previous in that major are dropped".

**Comment by zakkak** [comment]
> How about we do a cleanup with the LTS? Like "when LTS comes, all previous in that major are dropped".

I recall having some issues with keeping that many images up to date, but I don't recall what the issue was. @cescoffier might have a better memory :)

**Comment by cescoffier** [comment]
The deployment will fail, unfortunately. The whole deployment process is broken since multi-archs. Look at the multi-archs branch, which proposes a completely new approach to building the images.

**Comment by Karm** [comment]
> The deployment will fail, unfortunately. The whole deployment process is broken since multi-archs. Look at the multi-archs branch, which proposes a completely new approach to building the images.

I've seen the multi-archs branch. Not sure I understand how it's meant to work though.

@cescoffier Could you help me to understand what would be the best now, please? 

Having updated images up and running on quay is definitely a higher priority for us than having multiarch.

Should I remove the Mandrel multiarch from the current branch, do the update and iterate async later in the multi-arch branch?

**Comment by galderz** [comment]
> ... The whole deployment process is broken since multi-archs...

🙈

**Comment by galderz** [comment]
@cescoffier if my gift to you (https://github.com/quarkusio/quarkus-images/commit/21e25a3c3ae3e3f4a4bd02b1e76f6051c31729c0) is to problematic, why not revert it? As I already indicated in https://github.com/quarkusio/quarkus-images/pull/196, https://github.com/quarkusio/quarkus-images/commit/21e25a3c3ae3e3f4a4bd02b1e76f6051c31729c0 is only half of the job. You need the (hacked) code in the PR to be able to push things. So, I'd be very glad for my work to be reverted and unlock @Karm's and @gastaldi's PRs.

**Comment by galderz** [comment]
https://github.com/quarkusio/quarkus-images/pull/203 needs to be integrated before this PR can. Also, once integrated this PR might need to be reworked.

**Comment by Karm** [comment]
@galderz @zakkak I rebased, removed multiarch naming and also dropped old images.

**Comment by Karm** [comment]
O.K., that removal part was not a good move "Unable to find cekit module for version 21.2.0.2-Final-java11 - exiting"

**Review by galderz — APPROVED** [review]

**Review by gsmet — APPROVED** [review]
Nice work, thanks!

**Comment by Karm** [comment]
Can we have the rebuild triggered now?

https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags

**Comment by galderz** [comment]
@Karm Probably but I would maybe prefer to rebuild both Mandrel and GraalVM images at the same time so that they're available (roughly) at the same time. GraalVM PRs look good but still need merging (I can't do that).

**Pull request merged**
