### PR TITLE
Add mandrel 20.1.0.1.Final image

### PR DESCRIPTION
**Pull request by zakkak**
@cescoffier could you please:
* review
* merge if OK
* push the new image to quay.io and make it public? 

Thanks

### CODE REVIEW

**Comment by cescoffier** [comment]
Do we want to keep the 2 alphas?

**Comment by zakkak** [comment]
Thanks Clement 

> Do we want to keep the 2 alphas?

If there is no limit on the number of images I would prefer to keep them around.

**Comment by cescoffier** [comment]
@zakkak no there are no limits (as far as I know).

I'm asking because I'm starting considering having fewer images and provide only 1 image per major (GraalVM 19 would provide 19.3.3 for example). Of course for Mandrel we can keep having many.

**Comment by cescoffier** [comment]
BTW, images will be published Today, still working on a few PRs.

**Comment by zakkak** [comment]
> I'm asking because I'm starting considering having fewer images and provide only 1 image per major (GraalVM 19 would provide 19.3.3 for example). Of course for Mandrel we can keep having many.

Yes, that makes sense, but let's keep them around at least for now since this is our first final release.
Note that there is also demand for a `20.1` tag that would point to the latest 20.1.x.x image, making it simple for users to consume the latest (see https://github.com/graalvm/mandrel/issues/95).

> BTW, images will be published Today, still working on a few PRs.

Great, thanks a lot.

**Pull request merged**
